server:
  port: 18150

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5439/coupon_db
    username: root
    password: 1234

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 5443
      password: systempass
      timeout: 2s

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: coupon-service
