package com.destiny.sagaorchestrator.domain.entity;

public enum SagaStep {
    ORDER_CREATED_REQUEST,
    ORDER_CANCEL_REQUEST,

    USER_VALIDATE_SUCCESS,
    USER_VALIDATE_FAIL,

    PRODUCT_VALIDATION_SUCCESS,
    PRODUCT_VALIDATION_FAIL,

    STOCK_RESERVATION_SUCCESS,
    STOCK_RESERVATION_FAIL,

    COUPON_VALIDATION_SUCCESS,
    COUPON_VALIDATION_FAIL,

    COUPON_CANCEL_SUCCESS,
    COUPON_CANCEL_FAIL,

    PAYMENT_CREATE_SUCCESS,
    PAYMENT_CREATE_FAIL,

    PAYMENT_SUCCESS,
    PAYMENT_FAIL,

    PAYMENT_CANCEL_SUCCESS,
    PAYMENT_CANCEL_FAIL,

    ORDER_CREATE_SUCCESS
}
