@baseUrl = http://localhost:8080

### 회원가입 (customer)
POST {{baseUrl}}/v1/auths/signup
Content-Type: application/json

{
  "username": "user001",
  "password": "Test1234!",
  "nickname": "테스트유저1",
  "phone": "010-1234-5678",
  "email": "test001@example.com",
  "zipCode": "01234",
  "address1": "서울시 어딘가 1길 10",
  "address2": "101동 1001호",
  "birth": "1998-01-01"
}

### 회원가입 (관리자)
POST {{baseUrl}}/v1/auths/signup
Content-Type: application/json

{
  "username": "admin001",
  "password": "Admin1234!",
  "userRole": "MASTER",
  "adminToken": "my-super-secret-admin-token",
  "email": "admin@example.com"
}

### 로그인 성공 - 일반사용자
POST {{baseUrl}}/v1/auths/login
Content-Type: application/json

{
  "username": "user001",
  "password": "Test1234!"
}

> {%
  // 응답 헤더 값 가져오기
  const authorization = response.headers.valueOf("Authorization");
  const refreshCookie = response.headers.valueOf("Set-Cookie").split(";")[0].split("=")[1];
  const userId = response.body.data.userId;
  console.log(userId)


  // 전역 변수 저장
  client.global.set("ACCESS_TOKEN", authorization);
  client.global.set("REFRESH_TOKEN", refreshCookie);
  client.global.set("CUSTOMER_USER_ID", userId);
%}

### 로그인 성공 - 관리자
POST {{baseUrl}}/v1/auths/login
Content-Type: application/json

{
  "username": "admin001",
  "password": "Admin1234!"
}

> {%
  // 응답 헤더 값 가져오기
  const authorization = response.headers.valueOf("Authorization");
  const refreshCookie = response.headers.valueOf("Set-Cookie").split(";")[0].split("=")[1];
  const userId = response.body.data.userId;

  // 전역 변수 저장
  client.global.set("ADMIN_ACCESS_TOKEN", authorization);
  client.global.set("ADMIN_REFRESH_TOKEN", refreshCookie);
  client.global.set("ADMIN_USER_ID", userId);
%}

### 로그아웃 - 본인
POST {{baseUrl}}/v1/auths/logout
Content-Type: application/json
Authorization: {{ACCESS_TOKEN}}

### 로그아웃 - 다른 사용자 (실패)
POST {{baseUrl}}/v1/auths/logout?userId={{CUSTOMER_USER_ID}}
Content-Type: application/json
Authorization: {{ACCESS_TOKEN}}

### 로그아웃 - 다른 사용자 (성공)
POST {{baseUrl}}/v1/auths/logout?userId={{CUSTOMER_USER_ID}}
Content-Type: application/json
Authorization: {{ADMIN_ACCESS_TOKEN}}


### 회원 개별 조회
GET {{baseUrl}}/v1/users/{{CUSTOMER_USER_ID}}
Content-Type: application/json
Authorization: {{ACCESS_TOKEN}}

### 전체 목록 조회
GET {{baseUrl}}/v1/users
Authorization: {{ADMIN_ACCESS_TOKEN}}
Accept: application/json

### 기본 목록 조회 (삭제 안된 user, 최신순)
GET {{baseUrl}}/v1/users?deleted=false&userRole=CUSTOMER&size=10&isDescending=true
Authorization: {{ADMIN_ACCESS_TOKEN}}
Accept: application/json

### 회원 정보 수정
PATCH {{baseUrl}}/v1/users/{{CUSTOMER_USER_ID}}
Authorization: {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "nickname" : "수정된 사용자",
  "phone" : "010-1234-5678",
  "email" : "user@email.com"
}

### 비밀번호 수정
POST {{baseUrl}}/v1/users/{{CUSTOMER_USER_ID}}/password
Authorization: {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "currentPassword" : "Test1234!",
  "newPassword" : "Test123!"
}
