### 회원 개별 조회
GET http://localhost:18080/v1/users/550e8400-e29b-41d4-a716-111111110000
Content-Type: application/json

### 회원 정보 수정
PATCH http://localhost:18080/v1/users/550e8400-e29b-41d4-a716-111111110000
Content-Type: application/json

{
  "name" : "사용자",
  "phone" : "010-1234-5678",
  "email" : "user@email.com"
}

### 비밀번호 수정
POST http://localhost:18080/v1/users/550e8400-e29b-41d4-a716-111111110000/password
Content-Type: application/json

{
  "currentPassword" : "123!@#a",
  "newPassword" : "321#@!a"
}

### 회원 목록 조회
GET http://localhost:18080/v1/users
Content-Type: application/json

### 회원 상태 변경
POST http://localhost:18080/v1/users/550e8400-e29b-41d4-a716-111111110000/status?userStatus=ACTIVE
Content-Type: application/json